'use strict';

const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const options = {
  swaggerDefinition: {
    info: {
      title: 'ICE CREAM!',
      version: '0.0.1',
      description: 'Express API server with autogenerated Swagger documentation via swagger-jsdoc',
    },
    host: 'localhost:3000',
  },
  apis: ['./lib/routes/*.js'],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = (app) => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
};
